config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]

  root 'home#index'

  get '/beta-program' => 'beta_surveys#new'
  resources :beta_surveys, only: [:new, :create, :show]
  get '/beta-program/thank_you' => 'beta_surveys#thank_you'
  get '/current_customers' => redirect('https://www.boxbeestorage.com/simplestorage')
  get '/admin' => 'home#admin'

  get 'terms' => 'static_pages#terms'
  get 'privacy' => 'static_pages#terms'

  get '/instacart' => redirect('https://www.boxbeestorage.com/instacart')
  get '/simplestorage' => redirect('https://www.boxbeestorage.com/simplestorage')
  get '/jobs' => redirect('https://boxbee.workable.com')
  get '/boxbutler' => redirect('https://www.boxbeestorage.com/boxbutler')
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:admin]

  def index
  end

  def admin
    @companies = Company.all
    @companies_for_approval = Company.where(:hold=>true).count
    @beta_surveys = BetaSurvey.all
  end
end

app/helpers/home_helper.rb
module HomeHelper

end

app/views/home/admin.html.erb
<div class="container holder legacy">
  <h1>Welcome to the admin dashboard!</h1>
  <p>
    This summarizes information about you, companies, and surveys
  </p>
  <h3>You</h3>
  <p>
    Email: <%= current_user.email %>
  </p>

  <h3>Beta Program Surveys</h3>
  <p>
    Number of surveys filled out: <%= @beta_surveys.count %>
  </p>
  <h4>Survey results at a glance</h4>
  <table class="table">
    <tr>
      <th>ID</th>
      <th>Company name</th>
      <th>Contact name</th>
      <th>When survey was submitted</th>
      <th>Link to survey details</th>
    </tr>
    <% @beta_surveys.each do |survey| %>
      <tr>
        <td><%=survey.id%></td>
        <td><%=survey.company_name%></td>
        <td><%=survey.first_name %> <%=survey.last_name%></td>
        <td><%=survey.created_at %></td>
        <td><%=link_to "Go to this survey", survey%></td>
      </tr>
    <% end %>
  </table>

</div>

app/views/home/index.html.erb
<div class="hero-art-layer centered-div">
	<div class="centered-div" style="width:1000px;">
		<div class="row">
			<div class="col-xs-6" style="position:relative; height:488px; max-width:500px;">
				<div class="content-block">
					<h1>We Power Full-Service Storage</h1>
					<p>
						Self-storage companies (big and small) use Boxbee to offer on-demand pickup and delivery to their
						customers.
					</p>
				</div>
			</div>
			<div class="col-xs-6">
				<%= image_tag 'flying-macbook.png', size: '442x488' %>
			</div>
		</div>
	</div>
</div>
<div class="e2e-section" id="e2e-section">
	<div class="row">
		<div class="centered-div" style="width:1441px">
			<div class="col-xs-6">
				<%= image_tag 'laptop_phone.png', width: '823' %>
			</div>
			<div class="col-xs-6" style="max-width:500px; position:relative; height:541px;">
				<div class="content-block" style="top:40%; margin-left:100px;">
					<h1 style="color:black;">For Self-Storage Entrepreneurs</h1>
					<p>
						Our end-to-end software solution helps entrepreneurs manage an entire Full-Service Storage business. Signing up customers,
						accepting pickup and delivery appointments, and managing drivers and warehouses is brilliantly easy. No technical know-how needed.
					</p>
					<%= link_to 'Join our beta program', new_beta_survey_path, class: 'btn-cta-black', style: 'margin-top:20px;' %>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- <div class="apis-section">
	<div class="centered-div" style="width:1441px;">
		<div class="row">
			<div class="col-xs-6" style="padding-left:70px; height:300px;">
				<div class="content-block" style="top:50%;">
					<h1>
						For Self-Storage Companies
					</h1>
					<p style="color:white;">
						Our powerful APIs help established self-storage companies add on-demand pickup and delivery capabilities to their own website.
						Tools to manage everything from appointments to routing to inventory to billing can be integrated into their existing systems.
					</p>
					<%= mail_to 'api@boxbee.com', 'Email us to learn more', class: 'btn-cta-black', style: 'margin-top:20px;' %>
				</div>
			</div>
			<div class="col-xs-6" style="position:relative; height:300px;">
				<div class="content-block" style="top:40%; padding-left:70px;">
					<%= image_tag 'api.png' %>
					<%= image_tag 'web-development.png' %>
				</div>
			</div>
		</div>
	</div>
</div> -->

<div class="investors-section">
	<%= image_tag 'googleventures.png', style: 'margin: 0px 20px'%>
	<%= image_tag 'floodgate.png', style: 'margin: 0px 20px'%>
	<%= image_tag 'Lucas-logo.png', style: 'margin: 0px 20px'%>
	<%= image_tag 'metamorphic.png', style: 'margin: 0px 20px'%>
</div>

<div class="bottom-cta">
	<%= link_to 'Current Customer Login', 'https://www.boxbeestorage.com/simplestorage', class: 'btn-cta-black centered-div', style: 'margin-top:25px' %>
</div>