config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]

  root 'home#index'

  get '/beta-program' => 'beta_surveys#new'
  resources :beta_surveys, only: [:new, :create, :show]
  get '/beta-program/thank_you' => 'beta_surveys#thank_you'
  get '/current_customers' => redirect('https://www.boxbeestorage.com/simplestorage')
  get '/admin' => 'home#admin'

  get 'terms' => 'static_pages#terms'
  get 'privacy' => 'static_pages#terms'

  get '/instacart' => redirect('https://www.boxbeestorage.com/instacart')
  get '/simplestorage' => redirect('https://www.boxbeestorage.com/simplestorage')
  get '/jobs' => redirect('https://boxbee.workable.com')
  get '/boxbutler' => redirect('https://www.boxbeestorage.com/boxbutler')
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="row" style="padding-top:20px;">
		<div class="centered-div" style="color:gray;">
			<small>
				&copy; <%="#{DateTime.now.strftime('%Y')}"%> Boxbee, Inc. |
				<%= link_to 'Careers', 'https://boxbee.workable.com/' %> |
				<%= link_to 'Terms of Service', 'https://boxbee.com/terms'%>
			</small>
		</div>
	</div>
</div>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production" %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39050501-1', 'auto');
  ga('send', 'pageview');

  </script>
<% end %>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="header-content">
    <% if current_user %>
      <% if current_user.admin? %>
        <div class="admin-dropdown" style="float:right;">
          <button type="button" data-toggle="dropdown" class="btn-neutral" style="margin-left:5px;">Admin <i class="glyphicon glyphicon-chevron-down"></i></button>
          <ul class="dropdown-menu" style="left:auto; max-width:100px;">
            <li><%= link_to "Admin Home", admin_path %></li>
            <li><%= link_to "Admin Logout", destroy_user_session_path, method: 'delete'%></li>
          </ul>
        </div>
      <% else %>
        <%= link_to "Logout", destroy_user_session_path, method: 'delete', class: 'logout' %>
      <% end %>
    <% end %>
    <strong class="logo-top">
      <%= link_to image_tag("boxbee-logo.png"), root_path %>
    </strong>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boxbee: We Power Full-Service Storage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
  <meta name="description" content="Self-storage companies (big and small) use Boxbee to offer their customers on-demand pickup and delivery.">
  <meta name="keywords" content="storage, self-storage, on-demand storage, logistics, full-service storage">
</head>
<body>
  <div style="min-width:1441px;">
    <%= render partial: 'layouts/header' %>
    <% if flash[:notice]  %>
    <div class="alert alert-success flashes" id="flash-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:error]  %>
    <div class="alert alert-danger flashes" id="flash-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
    <% elsif flash[:alert]  %>
    <div class="alert alert-danger flashes" id="flash-alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
    <% end %>
    <%= yield %>
    <%=render partial: 'layouts/footer' %>
    <% render partial: 'layouts/google_analytics' %>
  </div>
</body>
</html>